/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ReadingsLazyImport = createFileRoute('/readings')()
const LimitsLazyImport = createFileRoute('/limits')()
const ControlLazyImport = createFileRoute('/control')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ReadingsLazyRoute = ReadingsLazyImport.update({
  path: '/readings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/readings.lazy').then((d) => d.Route))

const LimitsLazyRoute = LimitsLazyImport.update({
  path: '/limits',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/limits.lazy').then((d) => d.Route))

const ControlLazyRoute = ControlLazyImport.update({
  path: '/control',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/control.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlLazyImport
      parentRoute: typeof rootRoute
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsLazyImport
      parentRoute: typeof rootRoute
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/control': typeof ControlLazyRoute
  '/limits': typeof LimitsLazyRoute
  '/readings': typeof ReadingsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/control': typeof ControlLazyRoute
  '/limits': typeof LimitsLazyRoute
  '/readings': typeof ReadingsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/control': typeof ControlLazyRoute
  '/limits': typeof LimitsLazyRoute
  '/readings': typeof ReadingsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/control' | '/limits' | '/readings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/control' | '/limits' | '/readings'
  id: '__root__' | '/' | '/control' | '/limits' | '/readings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ControlLazyRoute: typeof ControlLazyRoute
  LimitsLazyRoute: typeof LimitsLazyRoute
  ReadingsLazyRoute: typeof ReadingsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ControlLazyRoute: ControlLazyRoute,
  LimitsLazyRoute: LimitsLazyRoute,
  ReadingsLazyRoute: ReadingsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/control",
        "/limits",
        "/readings"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/control": {
      "filePath": "control.lazy.tsx"
    },
    "/limits": {
      "filePath": "limits.lazy.tsx"
    },
    "/readings": {
      "filePath": "readings.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
