/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReadingsImport } from './routes/readings'
import { Route as LimitsImport } from './routes/limits'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ReadingsRoute = ReadingsImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRoute,
} as any)

const LimitsRoute = LimitsImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsImport
      parentRoute: typeof rootRoute
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/limits': typeof LimitsRoute
  '/readings': typeof ReadingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/limits': typeof LimitsRoute
  '/readings': typeof ReadingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/limits': typeof LimitsRoute
  '/readings': typeof ReadingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/limits' | '/readings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/limits' | '/readings'
  id: '__root__' | '/' | '/limits' | '/readings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LimitsRoute: typeof LimitsRoute
  ReadingsRoute: typeof ReadingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LimitsRoute: LimitsRoute,
  ReadingsRoute: ReadingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/limits",
        "/readings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/limits": {
      "filePath": "limits.tsx"
    },
    "/readings": {
      "filePath": "readings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
