/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ReadingsLazyImport = createFileRoute('/readings')()
const LimitsLazyImport = createFileRoute('/limits')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ReadingsLazyRoute = ReadingsLazyImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/readings.lazy').then((d) => d.Route))

const LimitsLazyRoute = LimitsLazyImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/limits.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsLazyImport
      parentRoute: typeof rootRoute
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/limits': typeof LimitsLazyRoute
  '/readings': typeof ReadingsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/limits': typeof LimitsLazyRoute
  '/readings': typeof ReadingsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/limits': typeof LimitsLazyRoute
  '/readings': typeof ReadingsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/limits' | '/readings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/limits' | '/readings'
  id: '__root__' | '/' | '/limits' | '/readings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LimitsLazyRoute: typeof LimitsLazyRoute
  ReadingsLazyRoute: typeof ReadingsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LimitsLazyRoute: LimitsLazyRoute,
  ReadingsLazyRoute: ReadingsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/limits",
        "/readings"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/limits": {
      "filePath": "limits.lazy.tsx"
    },
    "/readings": {
      "filePath": "readings.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
