import type { ControlsModel } from '../../sunspec/models/controls';
import type { InverterModel } from '../../sunspec/models/inverter';
import type { MeterModel } from '../../sunspec/models/meter';
import { generateMonitoringSample, type MonitoringSample } from './monitoring';
import type { InverterSunSpecConnection } from '../../sunspec/connection/inverter';
import type { MeterSunSpecConnection } from '../../sunspec/connection/meter';
import EventEmitter from 'events';
import { logger as pinoLogger } from '../../helpers/logger';
import type { NameplateModel } from '../../sunspec/models/nameplate';
import type { SettingsModel } from '../../sunspec/models/settings';
import type { StatusModel } from '../../sunspec/models/status';
import { promiseAllObject } from '../../helpers/promise';

const logger = pinoLogger.child({ module: 'SunSpecDataHelper' });

export class SunSpecDataHelper extends EventEmitter<{
    data: [
        {
            invertersData: {
                inverter: InverterModel;
                nameplate: NameplateModel;
                settings: SettingsModel;
                status: StatusModel;
                controls: ControlsModel;
            }[];
            metersData: {
                meter: MeterModel;
            }[];
            monitoringSample: MonitoringSample;
        },
    ];
}> {
    private invertersConnections: InverterSunSpecConnection[];
    private metersConnections: MeterSunSpecConnection[];

    constructor({
        invertersConnections,
        metersConnections,
    }: {
        invertersConnections: InverterSunSpecConnection[];
        metersConnections: MeterSunSpecConnection[];
    }) {
        super();

        this.invertersConnections = invertersConnections;
        this.metersConnections = metersConnections;

        void this.run();
    }

    async run() {
        const start = performance.now();

        try {
            const { invertersData, metersData } = await promiseAllObject({
                invertersData: Promise.all(
                    this.invertersConnections.map(async (inverter) => {
                        // it's not practical to parallelize these calls because the ModBus connection can only practically handle one request at a time
                        // the best we can do is parallelize multiple inverters and meters which are independent connections
                        return {
                            inverter: await inverter.getInverterModel(),
                            nameplate: await inverter.getNameplateModel(),
                            settings: await inverter.getSettingsModel(),
                            status: await inverter.getStatusModel(),
                            controls: await inverter.getControlsModel(),
                        };
                    }),
                ),
                metersData: Promise.all(
                    this.metersConnections.map(async (meter) => {
                        return {
                            meter: await meter.getMeterModel(),
                        };
                    }),
                ),
            });

            logger.trace({ invertersData, metersData }, 'received data');

            const monitoringSample = generateMonitoringSample({
                inverters: invertersData.map(({ inverter }) => inverter),
                meters: metersData.map(({ meter }) => meter),
            });

            logger.trace({ monitoringSample }, 'generated monitoring sample');

            const end = performance.now();

            logger.trace({ duration: end - start }, 'run time');

            this.emit('data', {
                invertersData,
                metersData,
                monitoringSample,
            });
        } catch (error) {
            logger.error({ error }, 'Failed to fetch SunSpec data');
        } finally {
            // this loop must meet sampling requirements and dynamic export requirements
            // Energex SEP2 Client Handbook specifies "As per the standard, samples should be taken every 200ms (10 cycles). If not capable of sampling this frequently, 1 second samples may be sufficient."
            // SA Power Networks – Dynamic Exports Utility Interconnection Handbook specifies "Average readings shall be generated by sampling at least every 5 seconds. For example, sample rates of less than 5 seconds are permitted."
            // we don't want to run this loop any more frequently than every 200ms to prevent overloading the SunSpec connection
            const end = performance.now();
            const duration = end - start;
            const delay = Math.max(200 - duration, 0);

            setTimeout(() => {
                void this.run();
            }, delay);
        }
    }
}
