import * as v from 'valibot';

export const meterAggregatesSchema = v.object({
    site: v.object({
        last_communication_time: v.string(),
        instant_power: v.number(),
        instant_reactive_power: v.number(),
        instant_apparent_power: v.number(),
        frequency: v.number(),
        energy_exported: v.number(),
        energy_imported: v.number(),
        instant_average_voltage: v.number(),
        instant_average_current: v.number(),
        i_a_current: v.number(),
        i_b_current: v.number(),
        i_c_current: v.number(),
        last_phase_voltage_communication_time: v.string(),
        last_phase_power_communication_time: v.string(),
        last_phase_energy_communication_time: v.string(),
        timeout: v.number(),
        num_meters_aggregated: v.number(),
        instant_total_current: v.number(),
    }),
    battery: v.object({
        last_communication_time: v.string(),
        instant_power: v.number(),
        instant_reactive_power: v.number(),
        instant_apparent_power: v.number(),
        frequency: v.number(),
        energy_exported: v.number(),
        energy_imported: v.number(),
        instant_average_voltage: v.number(),
        instant_average_current: v.number(),
        i_a_current: v.number(),
        i_b_current: v.number(),
        i_c_current: v.number(),
        last_phase_voltage_communication_time: v.string(),
        last_phase_power_communication_time: v.string(),
        last_phase_energy_communication_time: v.string(),
        timeout: v.number(),
        num_meters_aggregated: v.number(),
        instant_total_current: v.number(),
    }),
    load: v.object({
        last_communication_time: v.string(),
        instant_power: v.number(),
        instant_reactive_power: v.number(),
        instant_apparent_power: v.number(),
        frequency: v.number(),
        energy_exported: v.number(),
        energy_imported: v.number(),
        instant_average_voltage: v.number(),
        instant_average_current: v.number(),
        i_a_current: v.number(),
        i_b_current: v.number(),
        i_c_current: v.number(),
        last_phase_voltage_communication_time: v.string(),
        last_phase_power_communication_time: v.string(),
        last_phase_energy_communication_time: v.string(),
        timeout: v.number(),
        instant_total_current: v.number(),
    }),
    solar: v.object({
        last_communication_time: v.string(),
        instant_power: v.number(),
        instant_reactive_power: v.number(),
        instant_apparent_power: v.number(),
        frequency: v.number(),
        energy_exported: v.number(),
        energy_imported: v.number(),
        instant_average_voltage: v.number(),
        instant_average_current: v.number(),
        i_a_current: v.number(),
        i_b_current: v.number(),
        i_c_current: v.number(),
        last_phase_voltage_communication_time: v.string(),
        last_phase_power_communication_time: v.string(),
        last_phase_energy_communication_time: v.string(),
        timeout: v.number(),
        num_meters_aggregated: v.number(),
        instant_total_current: v.number(),
    }),
});

export const systemStatusSoeSchema = v.object({ percentage: v.number() });

export const metersSiteSchema = v.array(
    v.object({
        id: v.number(),
        location: v.string(),
        type: v.string(),
        cts: v.array(v.boolean()),
        inverted: v.array(v.boolean()),
        connection: v.object({
            short_id: v.string(),
            device_serial: v.string(),
            https_conf: v.optional(v.object({})),
        }),
        enable_grid_event_logging: v.optional(v.boolean()),
        Cached_readings: v.object({
            last_communication_time: v.string(),
            instant_power: v.number(),
            instant_reactive_power: v.number(),
            instant_apparent_power: v.number(),
            frequency: v.number(),
            energy_exported: v.number(),
            energy_imported: v.number(),
            instant_average_voltage: v.number(),
            instant_average_current: v.number(),
            i_a_current: v.optional(v.number()),
            i_b_current: v.optional(v.number()),
            i_c_current: v.optional(v.number()),
            last_phase_voltage_communication_time: v.string(),
            v_l1n: v.optional(v.number()),
            v_l2n: v.optional(v.number()),
            v_l3n: v.optional(v.number()),
            last_phase_power_communication_time: v.string(),
            real_power_a: v.optional(v.number()),
            real_power_b: v.optional(v.number()),
            real_power_c: v.optional(v.number()),
            reactive_power_a: v.optional(v.number()),
            reactive_power_b: v.optional(v.number()),
            reactive_power_c: v.optional(v.number()),
            last_phase_energy_communication_time: v.string(),
            serial_number: v.string(),
            version: v.string(),
            timeout: v.number(),
            instant_total_current: v.number(),
        }),
    }),
);
