import { expect, it } from 'vitest';
import { getCertificateLfdi } from './cert';

it('getCertificateLfdi returns valid LFDI', () => {
    // mock certificate
    const certString = `-----BEGIN CERTIFICATE-----
MIICYzCCAgmgAwIBAgIUanA0NK+hTe21hmSr9D+at8yQHDMwCgYIKoZIzj0EAwIw
gYYxCzAJBgNVBAYTAlhYMRIwEAYDVQQIDAlTdGF0ZU5hbWUxETAPBgNVBAcMCENp
dHlOYW1lMRQwEgYDVQQKDAtDb21wYW55TmFtZTEbMBkGA1UECwwSQ29tcGFueVNl
Y3Rpb25OYW1lMR0wGwYDVQQDDBRDb21tb25OYW1lT3JIb3N0bmFtZTAeFw0yNDA3
MTgwMDE3NDVaFw0zNDA3MTYwMDE3NDVaMIGGMQswCQYDVQQGEwJYWDESMBAGA1UE
CAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UECgwLQ29tcGFu
eU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTEdMBsGA1UEAwwUQ29t
bW9uTmFtZU9ySG9zdG5hbWUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQxyI6D
iUZ6W5Ks43E5gXXoVDDVAfyU4uZ2A4keC9LDtuVWbrBpc2fi9gKOfDVCF266ryHQ
/XdKtcNkJedL3Rceo1MwUTAdBgNVHQ4EFgQUdEYDPJta6xnRJIA4U1e+keJH09sw
HwYDVR0jBBgwFoAUdEYDPJta6xnRJIA4U1e+keJH09swDwYDVR0TAQH/BAUwAwEB
/zAKBggqhkjOPQQDAgNIADBFAiBfpNrZ7JZKboZn6apjDp52XrFtiGimRP+N8VhR
+ov7KgIhAIb+m/lof7dw7UJzAsQHHdE1r/Ln/p09KFAkymItyygB
-----END CERTIFICATE-----`;

    const lfdi = getCertificateLfdi(certString);

    expect(lfdi).toBe('B9A8A75E324D2312AD09F8DAF9C1295A3CE4142E');
});
