name: Lint and test
permissions:
    contents: read

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: 'pnpm'

            - run: pnpm install

            - name: Set up .env
              run: cp .env.example .env

            - run: pnpm run routes:generate

            - run: pnpm run lint

            - run: pnpm run build

            - name: Check for uncommitted files
              run: git diff --exit-code

            - run: pnpm test
